POST http://localhost:8080/transactions
Content-Type: application/json

{
  "amount": 150.00,
  "type": "Credit",
  "description": "Venda"
}

###

GET http://localhost:8080/balances/daily/2026-09-14
Accept: application/json

###
